### ISSUE TITLE
Criar tela de validação do email do usuário

### ISSUE THREAD

**Issue by Raul-vlb** [mapasculturais/plugin-MultipleLocalAuth#59]
Como está a tela atualmente (ainda do baseV1):

![Captura de tela de 2023-02-08 16-14-05.png](https://images.zenhubusercontent.com/625da13337da63063db5c51b/df71ff5d-a3f7-4b49-96cd-b1eccd25a259)

É preciso criar o layout para essa tela no baseV2

**Comment by patricknobre12** [comment]
segue a tela
https://www.figma.com/file/OYwb6bYY2rWDgZUN578Fij/Redesign---Entregas-(FINAIS)?node-id=3933%3A85160&t=5iMuDjCUp6avpli6-1
