### ISSUE TITLE
na página de gestão de usuários, o componente não deve pedir a senha atual do usuário

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/plugin-MultipleLocalAuth#64]
ver no BaseV1 o endpoint certinho para enviar a requisição, pq tb deve ser diferente

![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/d2adc6fe-f9da-4b5e-8aff-75ffa93b65a5)

**Comment by rafaelchavesfreitas** [comment]
logado como admin, não consegui trocar a senha de um outro usuário.

**Comment by daphnemartinsba** [comment]
A senha atual não é mais solicitada e a senha é alterada conforme critérios necessários informados na interface. Segue gif da jornada:

![64.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/78ddbf56-cdd3-4a3c-b79a-0b363c9e575e)
